[aiidalab]
title = Gas Modeling

[metadata]
name = aiidalab-gas-modeling
version = 0.1-alpha
author = Nathan Keilbart
author_email = keilbart1@llnl.gov
description = Gas Modeling for NAERM
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/nkeilbart/aiidalab-gas-modeling
project_urls =
    Logo = https://raw.githubusercontent.com/nkeilbart/aiidalab-gas-modeling/main/img/logo.png
    Documentation = https://github.com/nkeilbart/aiidalab-gas-modeling/#readme
    Bug Tracker = https://github.com/nkeilbart/aiidalab-gas-modeling/issues
classifiers =
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent
    Programming Language :: Python :: 3
    Development Status :: 1 - Planning

[options]
packages = find:
python_requires = >=3.7
install_requires =
    aiidalab>=21.09.0

[flake8]
ignore =
    E501  # Line length handled by black.
    W503  # Line break before binary operator, preferred formatting for black.
    E203  # Whitespace before ':', preferred formatting for black.
